### ISSUE TITLE
Unable to pull Packages after uploaded

### ISSUE THREAD

**Issue by MarkProminic** [tunisiano187/Docker-phpnuget#2]
Hello Tunisiano187,

Thanks for the work on getting this into a docker container. 

By chance have you ran into this issue?

https://github.com/kendarorg/PhpNuget/issues/59

I am not fully interpreting the solution at the end of this, maybe you could help us figure this out when we use this docker container?

![image](https://user-images.githubusercontent.com/50398495/104390402-35c07400-5503-11eb-85ed-c52be4d11bb0.png)

**Comment by tunisiano187** [comment]
no, i'm still trying to create the updated container, so it's in a still working on status ;-)

**Comment by tunisiano187** [comment]
i think it can be linked to the htaccess, so the rewrite may solve the problem.
I've pushed, it will be regenerated soon

**Comment by tunisiano187** [comment]
Can you try to pull the latest version and tell me if it works ?

**Comment by MarkProminic** [comment]
I've submitted a pull request. Let me know what you think
